[2025-04-09T05:16:24.658+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-09T05:16:24.680+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: RSS.init.set_connections scheduled__2025-04-09T04:01:00+00:00 [queued]>
[2025-04-09T05:16:24.687+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: RSS.init.set_connections scheduled__2025-04-09T04:01:00+00:00 [queued]>
[2025-04-09T05:16:24.688+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-09T05:16:24.714+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): init.set_connections> on 2025-04-09 04:01:00+00:00
[2025-04-09T05:16:24.728+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=67) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-09T05:16:24.729+0000] {standard_task_runner.py:63} INFO - Started process 78 to run task
[2025-04-09T05:16:24.730+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'RSS', 'init.set_connections', 'scheduled__2025-04-09T04:01:00+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/RSS_DAG.py', '--cfg-path', '/tmp/tmptk8b9y4i']
[2025-04-09T05:16:24.732+0000] {standard_task_runner.py:91} INFO - Job 176: Subtask init.set_connections
[2025-04-09T05:16:24.778+0000] {task_command.py:426} INFO - Running <TaskInstance: RSS.init.set_connections scheduled__2025-04-09T04:01:00+00:00 [running]> on host 5986bb29e517
[2025-04-09T05:16:24.865+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='RSS' AIRFLOW_CTX_TASK_ID='init.set_connections' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T04:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-09T04:01:00+00:00'
[2025-04-09T05:16:24.866+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-09T05:16:24.879+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-09T05:16:24.880+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '*** connections import /opt/***/connections.json']
[2025-04-09T05:16:24.904+0000] {subprocess.py:86} INFO - Output:
[2025-04-09T05:16:27.390+0000] {subprocess.py:93} INFO - [[34m2025-04-09T05:16:27.389+0000[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2025-04-09T05:16:27.397+0000] {subprocess.py:93} INFO - Could not import connection postgres_con: connection already exists.
[2025-04-09T05:16:27.397+0000] {subprocess.py:93} INFO - Could not import connection clickhouse_conn: connection already exists.
[2025-04-09T05:16:27.398+0000] {subprocess.py:93} INFO - Could not import connection rabbitmq_conn: connection already exists.
[2025-04-09T05:16:27.398+0000] {subprocess.py:93} INFO - Could not import connection mongo_conn: connection already exists.
[2025-04-09T05:16:27.399+0000] {subprocess.py:93} INFO - Could not import connection redis_conn: connection already exists.
[2025-04-09T05:16:27.791+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-09T05:16:27.794+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-09T05:16:27.820+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=RSS, task_id=init.set_connections, run_id=scheduled__2025-04-09T04:01:00+00:00, execution_date=20250409T040100, start_date=20250409T051624, end_date=20250409T051627
[2025-04-09T05:16:27.870+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-09T05:16:27.883+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-09T05:16:27.888+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
