[2025-04-07T08:05:21.007+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: RSS.init.set_variables scheduled__2025-01-03T09:01:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2025-04-07T08:31:55.343+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: RSS.init.set_variables scheduled__2025-01-03T09:01:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
